# Copyright 2015 Zuercher Hochschule fuer Angewandte Wissenschaften
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
heat_template_version: 2013-05-23

description: Heat template to deploy a SmartMachine and a KVM Machine in SDC

parameters:
  sapi_endpoint:
    type: string
    default: 10.0.0.26
    description : The admin-IP address of the sapi instance

  user_uuid:
    type: string
    default: 72f70341-b227-4051-befd-b0d5e1588a6d
    description: UUID of the owner of the machines

  package:
    type: string
    default: b1abec1a-80e5-ea9e-e091-8f2d67feb252
    description: The package uuid to use

  external_network_uuid:
    type: string
    default: f3d68d27-e311-491a-9c7f-d2a8d386e6e6
    description: The external network uuid to use

  user_script:
    type: string
    default: touch /test
    description: shell script to be run in the machine

  ubuntu_image:
    type: string
    default: d2ba0f30-bbe8-11e2-a9a2-6bc116856d85
    description: uuid of ubuntu image

  centos_image:
    type: string
    default: 02dbab66-a70a-11e4-819b-b3dc41b361d6
    description: uuid of centos image

  smart_machine_image:
    type: string
    default: 62f148f8-6e84-11e4-82c5-efca60348b9f
    description: The image uuid to use for the smart machine

resources:
  smartmachine:
    type: SDC::Compute::SmartMachine
    properties:
      sapi_endpoint: { get_param: sapi_endpoint }
      user_uuid: { get_param: user_uuid }
      instance_alias: sm_1
      package: { get_param: package }
      image: { get_param: smart_machine_image }
      networks: { get_param: external_network_uuid }
      user_script: { get_param: user_script }

  centos:
      type: SDC::Compute::KVM
      properties:
        sapi_endpoint: { get_param: sapi_endpoint }
        user_uuid: { get_param: user_uuid }
        instance_alias: centos_1
        package: { get_param: package }
        image: { get_param: centos_image }
        networks: { get_param: external_network_uuid }
        user_script: { get_param: user_script }

  ubuntu:
      type: SDC::Compute::KVM
      properties:
        sapi_endpoint: { get_param: sapi_endpoint }
        user_uuid: { get_param: user_uuid }
        instance_alias: ubuntu_1
        package: { get_param: package }
        image: { get_param: centos_image }
        networks: { get_param: external_network_uuid }
        user_script: { get_param: user_script }